<?php

namespace Shop\ProductBundle\Repository;

/**
 * CacheTags
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use \Doctrine\ORM\EntityRepository;

class HashTagsRepository extends EntityRepository
{
    /**
     * Ищем все перечисленные теги и добавлям их к продукту
     *
     * @param array $data
     *
     * @return array
    */
    public function findByNameTags(array $data)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                    SELECT h FROM ShopProductBundle:HashTags h
                    WHERE h.name IN (:tags)
                ')->setParameter('tags', $data);


        return $query->getResult();
    }

    /**
     * Ищем все перечисленные теги у продукта
     *
     * @param int $id
     *
     * @return array
     */
    public function findByTags($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                    SELECT h FROM ShopProductBundle:HashTags h
                    LEFT JOIN h.product p
                    WHERE p.id = :id
                ')->setParameter('id', $id);


        return $query->getResult();
    }
}
