<?php

namespace Shop\AddProductsBundle\Repository;

/**
 * CacheTags
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use \Doctrine\ORM\EntityRepository;

class CacheTagsRepository extends EntityRepository
{
}
